### ISSUE TITLE
Is this the official mirrow?

### ISSUE THREAD

**Issue by kostaz** [cjlano/freertos#6]
Hi guys,

I'll like to clone from this repo, but some questions need to be asked first...

Some important questions:
 - I this the official mirror that has **the same** code as SVN repo on Source Forge (https://sourceforge.net/p/freertos/code/HEAD/tree/)?
 - Is this mirror being update from time to time? (If yes, how often?)
 - Can you please post the extract commands that you used (tutoria-like) to convert SVN repo to this git?

Thanks,
--- KostaZ

**Comment by cjlano** [comment]
Hello,

- No, this is not an official repo, but I try to maintain it as up-to-date as possible.
- I have a set up which update this repo once a day. It had misbehave lately due to a machine upgrade. It is fixed now.
- Here is the script I use to maintain this repo:
https://gist.github.com/cjlano/7f8cfd6e755d19c6cf0ffe2297da4f50

Enjoy!
